import type { Metadata } from "next";

import { LegalPage } from "../components/LegalPage";
import { getPageMetadata } from "@/lib/seo";

export const metadata: Metadata = getPageMetadata("privacy");

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Website Privacy Policy"
      title="Privacy Policy"
      lastUpdated="July 21, 2026"
      intro={[
        "Welcome to our website. We are an IT consulting firm. We respect your privacy and are committed to protecting your personally identifiable information, or Personal Data.",
        "This Privacy Policy explains how we collect, use, and protect your information when you visit our website, use our contact forms, or inquire about our services.",
      ]}
      sections={[
        {
          title: "Information We Collect",
          body: [
            "We collect information that you voluntarily provide to us, as well as data automatically generated by your visit.",
          ],
          list: [
            "Information You Provide: When you fill out our contact or inquiry forms to request IT consulting services, we collect your name, business email address, phone number, company name, and any specific technical or project details you include in your message.",
            "Information Collected Automatically (Cookies): We use Google Analytics to collect anonymous technical data. This includes your IP address, browser type, device information, operating system, pages viewed, time spent on the site, and the website that referred you to us.",
          ],
        },
        {
          title: "How We Use Your Information",
          body: [
            "We use the data we collect strictly for professional business purposes:",
          ],
          list: [
            "To respond to your inquiries, provide consulting quotes, and fulfill your requests for information.",
            "To manage and qualify prospective business leads.",
            "To analyze website traffic trends and improve our website's performance and user experience.",
          ],
        },
        {
          title: "Sharing and Disclosing Your Data",
          list: [
            "No Selling or Renting: We do not sell, rent, or trade your lead information or personal data to third-party advertisers or data brokers.",
            "No Retargeting: We do not use remarketing pixels, behavioral tracking for advertising, or target you with display ads across the internet.",
            "Service Providers: We may share your data with trusted third-party service providers, such as website hosting companies or our secure internal Customer Relationship Management (CRM) platform, solely to help run our business operations. These providers are bound by strict confidentiality agreements.",
            "Legal Requirements: We may disclose your information if required to do so by law, or in response to valid legal requests by public authorities, such as a court or government agency.",
          ],
        },
        {
          title: "Cookies and Your Control",
          body: [
            "Google Analytics utilizes tracking cookies to gather traffic data. You can control or restrict cookies in the following ways:",
          ],
          list: [
            "Adjusting your internet browser settings to block or delete cookies.",
            "Using the official Google Analytics Opt-out Browser Add-on to prevent your data from being used by Google Analytics.",
          ],
        },
        {
          title: "Data Security",
          body: [
            "We implement appropriate technical and organizational security measures to protect your Personal Data against unauthorized access, alteration, disclosure, or destruction. However, please note that no method of transmission over the internet is 100% secure.",
          ],
        },
        {
          title: "Your Rights",
          body: [
            "Depending on your location, you may have the right to access, correct, update, or request the deletion of the personal information we hold about you. If you wish to exercise these rights, please contact us using the information below.",
          ],
        },
        {
          title: "Contact Us",
          body: [
            "If you have any questions about this Privacy Policy, please contact us at:",
          ],
          list: [
            "Email: info@jethavictus.com",
            "Branch locations: Corporate headquarters, technology delivery center, regional consulting office, and client experience center by appointment.",
          ],
        },
      ]}
    />
  );
}
